# Generated by Django 6.0.3 on 2026-04-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='iv',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
