# Generated by Django 6.0.3 on 2026-04-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recording_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name_iv',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='name',
            field=models.TextField(),
        ),
    ]
