# Generated by Django 6.0.3 on 2026-04-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recording_name_iv_alter_recording_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
