# Generated by Django 6.0.3 on 2026-04-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='accounts.folder'),
        ),
    ]
