# Generated by Django 6.0.3 on 2026-04-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recording_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
    ]
