# Generated by Django 6.0.3 on 2026-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_folder_folder_salt_folder_has_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='password_check',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='password_check_iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
