# Generated by Django 6.0.3 on 2026-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_folder_password_check_folder_password_check_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='decoy_check',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='decoy_check_iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='decoy_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
