# Generated by Django 6.0.3 on 2026-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_folder_decoy_check_folder_decoy_check_iv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='is_decoy',
            field=models.BooleanField(default=False),
        ),
    ]
