# Generated by Django 6.0.3 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recording_is_decoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
