# Generated by Django 6.0.3 on 2026-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_recording_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
